name: acme
description: A Health tracking application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  get: ^4.6.1
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.jpg
    - assets/splash.json
